% EXPECT: warnings = 0
% EXPECT: s1 = matrix[3 x 4]
% EXPECT: s2 = scalar
% EXPECT: s3 = matrix[n x m]
% EXPECT: c1 = matrix[3 x 4]
% EXPECT: t1 = matrix[3 x 4]
% EXPECT: as1 = matrix[3 x 4]
% EXPECT: ac1 = matrix[3 x 4]
% EXPECT: at1 = matrix[3 x 4]
% EXPECT: e1 = matrix[3 x 4]
% EXPECT: l1 = matrix[3 x 4]
% EXPECT: l2_1 = matrix[3 x 4]
% EXPECT: l10_1 = matrix[3 x 4]
% EXPECT: ce1 = matrix[3 x 4]
% EXPECT: f1 = matrix[3 x 4]
% EXPECT: r1 = matrix[3 x 4]
% EXPECT: sg1 = matrix[3 x 4]
% EXPECT: re1 = matrix[3 x 4]
% EXPECT: im1 = matrix[3 x 4]
% EXPECT: m1 = matrix[2 x 3]
% EXPECT: m2 = scalar
% EXPECT: m3 = matrix[2 x 3]
% EXPECT: a1 = matrix[n x m]

A = zeros(3, 4);
s1 = sin(A);
s2 = cos(5);
s3 = exp(ones(n, m));
c1 = cos(A);
t1 = tan(A);
as1 = asin(A);
ac1 = acos(A);
at1 = atan(A);
e1 = exp(A);
l1 = log(A);
l2_1 = log2(A);
l10_1 = log10(A);
ce1 = ceil(A);
f1 = floor(A);
r1 = round(A);
sg1 = sign(A);
re1 = real(A);
im1 = imag(A);
m1 = mod(zeros(2, 3), ones(2, 3));
m2 = mod(5, 3);
m3 = rem(zeros(2, 3), ones(2, 3));
a1 = atan2(ones(n, m), zeros(n, m));
