% EXPECT: warnings = 0
% EXPECT: r1 = matrix[1 x 4]
% EXPECT: r2 = matrix[3 x 1]
% EXPECT: r3 = scalar
% EXPECT: r4 = matrix[1 x 3]
% EXPECT: r5 = matrix[2 x 3]
% EXPECT: p1 = matrix[1 x 4]
% EXPECT: mn1 = matrix[1 x 4]
% EXPECT: an1 = matrix[1 x 4]
% EXPECT: al1 = matrix[1 x 4]
% EXPECT: c1 = matrix[3 x 4]
% EXPECT: c2 = matrix[3 x 4]
% EXPECT: d1 = matrix[4 x 3]
% EXPECT: d2 = matrix[1 x 4]
% EXPECT: d3 = matrix[(n-1) x m]

A = zeros(3, 4);
r1 = sum(A);
r2 = sum(A, 2);
r3 = sum(5);
B = zeros(2, 3);
r4 = min(B);
r5 = min(B, ones(2, 3));
p1 = prod(A);
mn1 = mean(A);
an1 = any(A);
al1 = all(A);
c1 = cumsum(A);
c2 = cumprod(A);
C = zeros(5, 3);
d1 = diff(C);
D = zeros(1, 5);
d2 = diff(D);
E = zeros(n, m);
d3 = diff(E);
