// Conformal: Static Shape Analysis for MATLAB
// author: matrix[1 x 1] Ethan Doughty, 2026
//
// Discriminated union of every W_* warning code the analyzer can emit,
// replacing earlier stringly-typed identifiers with a compiler-checked
// enum. Compiled early in the F# build order so any module can
// reference a code without pulling in Diagnostics.

module WarningCodes

type WarningCode =
    // Shape errors
    | W_INNER_DIM_MISMATCH
    | W_ELEMENTWISE_MISMATCH
    | W_HORZCAT_ROW_MISMATCH
    | W_VERTCAT_COL_MISMATCH
    | W_RESHAPE_MISMATCH
    | W_MLDIVIDE_DIM_MISMATCH
    | W_MATRIX_POWER_NON_SQUARE
    | W_CONCAT_TYPE_MISMATCH
    // Type errors
    | W_ARITHMETIC_TYPE_MISMATCH
    | W_TRANSPOSE_TYPE_MISMATCH
    | W_NEGATE_TYPE_MISMATCH
    | W_NOT_TYPE_MISMATCH
    | W_STRING_ARITHMETIC
    // Indexing
    | W_TOO_MANY_INDICES
    | W_RANGE_NON_SCALAR
    | W_INVALID_RANGE
    | W_NON_SCALAR_INDEX
    | W_INDEX_OUT_OF_BOUNDS
    | W_INDEX_ASSIGN_TYPE_MISMATCH
    // Function calls
    | W_UNKNOWN_FUNCTION
    | W_FUNCTION_ARG_COUNT_MISMATCH
    | W_PROCEDURE_IN_EXPR
    | W_RECURSIVE_FUNCTION
    | W_RECURSIVE_LAMBDA
    // Multi-assign
    | W_MULTI_ASSIGN_NON_CALL
    | W_MULTI_ASSIGN_COUNT_MISMATCH
    // Lambda
    | W_LAMBDA_CALL_APPROXIMATE
    | W_LAMBDA_ARG_COUNT_MISMATCH
    // Struct/cell
    | W_STRUCT_FIELD_NOT_FOUND
    | W_FIELD_ACCESS_NON_STRUCT
    | W_CURLY_INDEXING_NON_CELL
    | W_CELL_ASSIGN_NON_CELL
    // Control flow
    | W_RETURN_OUTSIDE_FUNCTION
    | W_BREAK_OUTSIDE_LOOP
    | W_CONTINUE_OUTSIDE_LOOP
    // Interval/constraint
    | W_DIVISION_BY_ZERO
    | W_POSSIBLY_NEGATIVE_DIM
    | W_CONSTRAINT_CONFLICT
    // Comparison/logical
    | W_SUSPICIOUS_COMPARISON
    | W_MATRIX_COMPARISON
    | W_LOGICAL_OP_NON_SCALAR
    // Reassignment
    | W_REASSIGN_INCOMPATIBLE
    // Parser/recovery
    | W_UNSUPPORTED_STMT
    | W_EXTERNAL_PARSE_ERROR
    | W_END_OUTSIDE_INDEXING
    // Matrix literal
    | W_MATRIX_LIT_EMPTY_ROW
    // cellfun
    | W_CELLFUN_NON_UNIFORM
    // Coder
    | W_CODER_VARIABLE_SIZE
    | W_CODER_CELL_ARRAY
    | W_CODER_DYNAMIC_FIELD
    | W_CODER_TRY_CATCH
    | W_CODER_UNSUPPORTED_BUILTIN
    | W_CODER_RECURSION
    // Strict mode (pseudo-code used in LspDiagnostics)
    | W_STRICT_MODE

/// Serialize a WarningCode to its canonical string representation.
/// Output is byte-identical to the previous stringly-typed codes.
/// Use this at all serialization boundaries (CLI output, LSP protocol).
let codeString (c: WarningCode) : string =
    match c with
    | W_INNER_DIM_MISMATCH          -> "W_INNER_DIM_MISMATCH"
    | W_ELEMENTWISE_MISMATCH        -> "W_ELEMENTWISE_MISMATCH"
    | W_HORZCAT_ROW_MISMATCH        -> "W_HORZCAT_ROW_MISMATCH"
    | W_VERTCAT_COL_MISMATCH        -> "W_VERTCAT_COL_MISMATCH"
    | W_RESHAPE_MISMATCH            -> "W_RESHAPE_MISMATCH"
    | W_MLDIVIDE_DIM_MISMATCH       -> "W_MLDIVIDE_DIM_MISMATCH"
    | W_MATRIX_POWER_NON_SQUARE     -> "W_MATRIX_POWER_NON_SQUARE"
    | W_CONCAT_TYPE_MISMATCH        -> "W_CONCAT_TYPE_MISMATCH"
    | W_ARITHMETIC_TYPE_MISMATCH    -> "W_ARITHMETIC_TYPE_MISMATCH"
    | W_TRANSPOSE_TYPE_MISMATCH     -> "W_TRANSPOSE_TYPE_MISMATCH"
    | W_NEGATE_TYPE_MISMATCH        -> "W_NEGATE_TYPE_MISMATCH"
    | W_NOT_TYPE_MISMATCH           -> "W_NOT_TYPE_MISMATCH"
    | W_STRING_ARITHMETIC           -> "W_STRING_ARITHMETIC"
    | W_TOO_MANY_INDICES            -> "W_TOO_MANY_INDICES"
    | W_RANGE_NON_SCALAR            -> "W_RANGE_NON_SCALAR"
    | W_INVALID_RANGE               -> "W_INVALID_RANGE"
    | W_NON_SCALAR_INDEX            -> "W_NON_SCALAR_INDEX"
    | W_INDEX_OUT_OF_BOUNDS         -> "W_INDEX_OUT_OF_BOUNDS"
    | W_INDEX_ASSIGN_TYPE_MISMATCH  -> "W_INDEX_ASSIGN_TYPE_MISMATCH"
    | W_UNKNOWN_FUNCTION            -> "W_UNKNOWN_FUNCTION"
    | W_FUNCTION_ARG_COUNT_MISMATCH -> "W_FUNCTION_ARG_COUNT_MISMATCH"
    | W_PROCEDURE_IN_EXPR           -> "W_PROCEDURE_IN_EXPR"
    | W_RECURSIVE_FUNCTION          -> "W_RECURSIVE_FUNCTION"
    | W_RECURSIVE_LAMBDA            -> "W_RECURSIVE_LAMBDA"
    | W_MULTI_ASSIGN_NON_CALL       -> "W_MULTI_ASSIGN_NON_CALL"
    | W_MULTI_ASSIGN_COUNT_MISMATCH -> "W_MULTI_ASSIGN_COUNT_MISMATCH"
    | W_LAMBDA_CALL_APPROXIMATE     -> "W_LAMBDA_CALL_APPROXIMATE"
    | W_LAMBDA_ARG_COUNT_MISMATCH   -> "W_LAMBDA_ARG_COUNT_MISMATCH"
    | W_STRUCT_FIELD_NOT_FOUND      -> "W_STRUCT_FIELD_NOT_FOUND"
    | W_FIELD_ACCESS_NON_STRUCT     -> "W_FIELD_ACCESS_NON_STRUCT"
    | W_CURLY_INDEXING_NON_CELL     -> "W_CURLY_INDEXING_NON_CELL"
    | W_CELL_ASSIGN_NON_CELL        -> "W_CELL_ASSIGN_NON_CELL"
    | W_RETURN_OUTSIDE_FUNCTION     -> "W_RETURN_OUTSIDE_FUNCTION"
    | W_BREAK_OUTSIDE_LOOP          -> "W_BREAK_OUTSIDE_LOOP"
    | W_CONTINUE_OUTSIDE_LOOP       -> "W_CONTINUE_OUTSIDE_LOOP"
    | W_DIVISION_BY_ZERO            -> "W_DIVISION_BY_ZERO"
    | W_POSSIBLY_NEGATIVE_DIM       -> "W_POSSIBLY_NEGATIVE_DIM"
    | W_CONSTRAINT_CONFLICT         -> "W_CONSTRAINT_CONFLICT"
    | W_SUSPICIOUS_COMPARISON       -> "W_SUSPICIOUS_COMPARISON"
    | W_MATRIX_COMPARISON           -> "W_MATRIX_COMPARISON"
    | W_LOGICAL_OP_NON_SCALAR       -> "W_LOGICAL_OP_NON_SCALAR"
    | W_REASSIGN_INCOMPATIBLE       -> "W_REASSIGN_INCOMPATIBLE"
    | W_UNSUPPORTED_STMT            -> "W_UNSUPPORTED_STMT"
    | W_EXTERNAL_PARSE_ERROR        -> "W_EXTERNAL_PARSE_ERROR"
    | W_END_OUTSIDE_INDEXING        -> "W_END_OUTSIDE_INDEXING"
    | W_MATRIX_LIT_EMPTY_ROW        -> "W_MATRIX_LIT_EMPTY_ROW"
    | W_CELLFUN_NON_UNIFORM         -> "W_CELLFUN_NON_UNIFORM"
    | W_CODER_VARIABLE_SIZE         -> "W_CODER_VARIABLE_SIZE"
    | W_CODER_CELL_ARRAY            -> "W_CODER_CELL_ARRAY"
    | W_CODER_DYNAMIC_FIELD         -> "W_CODER_DYNAMIC_FIELD"
    | W_CODER_TRY_CATCH             -> "W_CODER_TRY_CATCH"
    | W_CODER_UNSUPPORTED_BUILTIN   -> "W_CODER_UNSUPPORTED_BUILTIN"
    | W_CODER_RECURSION             -> "W_CODER_RECURSION"
    | W_STRICT_MODE                 -> "W_STRICT_MODE"

// Lookup map from canonical string to WarningCode.
// Built without reflection; must be updated whenever WarningCode cases are added or removed.
let private codeMap : Map<string, WarningCode> =
    [ W_INNER_DIM_MISMATCH; W_ELEMENTWISE_MISMATCH; W_HORZCAT_ROW_MISMATCH
      W_VERTCAT_COL_MISMATCH; W_RESHAPE_MISMATCH; W_MLDIVIDE_DIM_MISMATCH
      W_MATRIX_POWER_NON_SQUARE; W_CONCAT_TYPE_MISMATCH
      W_ARITHMETIC_TYPE_MISMATCH; W_TRANSPOSE_TYPE_MISMATCH
      W_NEGATE_TYPE_MISMATCH; W_NOT_TYPE_MISMATCH; W_STRING_ARITHMETIC
      W_TOO_MANY_INDICES; W_RANGE_NON_SCALAR; W_INVALID_RANGE
      W_NON_SCALAR_INDEX; W_INDEX_OUT_OF_BOUNDS; W_INDEX_ASSIGN_TYPE_MISMATCH
      W_UNKNOWN_FUNCTION; W_FUNCTION_ARG_COUNT_MISMATCH
      W_PROCEDURE_IN_EXPR; W_RECURSIVE_FUNCTION; W_RECURSIVE_LAMBDA
      W_MULTI_ASSIGN_NON_CALL; W_MULTI_ASSIGN_COUNT_MISMATCH
      W_LAMBDA_CALL_APPROXIMATE; W_LAMBDA_ARG_COUNT_MISMATCH
      W_STRUCT_FIELD_NOT_FOUND; W_FIELD_ACCESS_NON_STRUCT
      W_CURLY_INDEXING_NON_CELL; W_CELL_ASSIGN_NON_CELL
      W_RETURN_OUTSIDE_FUNCTION; W_BREAK_OUTSIDE_LOOP; W_CONTINUE_OUTSIDE_LOOP
      W_DIVISION_BY_ZERO; W_POSSIBLY_NEGATIVE_DIM; W_CONSTRAINT_CONFLICT
      W_SUSPICIOUS_COMPARISON; W_MATRIX_COMPARISON; W_LOGICAL_OP_NON_SCALAR
      W_REASSIGN_INCOMPATIBLE; W_UNSUPPORTED_STMT; W_EXTERNAL_PARSE_ERROR
      W_END_OUTSIDE_INDEXING; W_MATRIX_LIT_EMPTY_ROW; W_CELLFUN_NON_UNIFORM
      W_CODER_VARIABLE_SIZE; W_CODER_CELL_ARRAY; W_CODER_DYNAMIC_FIELD
      W_CODER_TRY_CATCH; W_CODER_UNSUPPORTED_BUILTIN; W_CODER_RECURSION
      W_STRICT_MODE ]
    |> List.map (fun c -> (codeString c, c))
    |> Map.ofList

/// Deserialize a string to WarningCode option.
/// Returns None for unrecognized code strings.
let tryParseCode (s: string) : WarningCode option =
    codeMap.TryFind s
